sudo : required
services:
  - docker

before_install:
  - docker build -t antonioc74/docker-react -f Dockerfile.dev .

script:
  - docker run  antonioc74/docker-react npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-209160698439"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
